# Generated by Django 5.0.6 on 2024-06-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_db',
            name='image',
            field=models.ImageField(default=' ', upload_to='cus_img'),
        ),
    ]
